"""Nextflow subprocess orchestration — the headline capability.

This module launches a *real* Nextflow run. `--outdir` lives on Backblaze B2 over
the S3-compatible API — Nextflow publishes results there and stages the s3://
samplesheet/FASTQ inputs from there too. `workDir` is a LOCAL (POSIX) directory:
the bundled demo pipeline (`pipelines/demo/nextflow.config`) sets
`process.executor = 'local'`, and Nextflow's local executor requires a POSIX work
directory — an `s3://` workDir is only supported by a cloud executor (e.g. AWS
Batch) or Fusion, neither of which this Docker-free demo uses. It generates a
`nextflow.config` that points Nextflow's AWS client at the B2 endpoint (derived
from `B2_REGION`) with path-style access; credentials are injected through the
subprocess environment, never written to the config file on disk.

No boto3 here (that stays in repo/). This module reads settings, shells out to
`nextflow`, and calls the runs repo to persist the log + status transitions.
Graceful degrade: if the `nextflow` binary or Java is missing, the caller marks
the run `blocked` with an install hint instead of crashing.

`run_subprocess` and `engine_status` are deliberate seams the tests patch, so
`pnpm verify` stays non-live and credential-free.
"""

import contextlib
import logging
import os
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from app.config import settings
from app.repo import runs as runs_repo

logger = logging.getLogger(__name__)

# services/api/app/service/nextflow.py -> parents[4] == repo root.
_REPO_ROOT = Path(__file__).resolve().parents[4]
_DEMO_PIPELINE = _REPO_ROOT / "pipelines" / "demo" / "main.nf"

# Cap a single demo run so a wedged subprocess can never pin the worker forever.
_RUN_TIMEOUT_SECONDS = 900


def engine_status() -> tuple[bool, str]:
    """(available, hint). `available` is True only when both the Nextflow binary
    and Java are on PATH. The hint tells the operator how to unblock a run."""
    nf = shutil.which(settings.nextflow_bin)
    java = shutil.which(settings.java_bin)
    if nf and java:
        return True, ""
    missing = [name for name, found in (("Nextflow", nf), ("Java", java)) if not found]
    hint = (
        f"{' and '.join(missing)} not found on PATH. Install Nextflow "
        "(https://www.nextflow.io/docs/latest/install.html) and a JDK 17+ "
        "(e.g. `brew install openjdk@17` or `apt install openjdk-17-jre`), then "
        "relaunch this run. The run record and its inputs are preserved."
    )
    return False, hint


def pipeline_source(pipeline: str) -> str:
    """Resolve a pipeline value to something `nextflow run` accepts."""
    if pipeline == "demo":
        return str(_DEMO_PIPELINE)
    # nf-core/sarek | nf-core/rnaseq — Nextflow pulls these from GitHub; they
    # need network access and a container engine (documented realistic path).
    return pipeline


def _scratch_root(run_id: str) -> Path:
    """The run's local scratch dir, WITHOUT creating it (safe to call at
    create-run time, before the run has ever launched)."""
    root = Path(settings.run_scratch_dir)
    if not root.is_absolute():
        root = _REPO_ROOT / root
    return root / run_id


def _scratch_dir(run_id: str) -> Path:
    scratch = _scratch_root(run_id)
    scratch.mkdir(parents=True, exist_ok=True)
    return scratch


def local_work_dir(run_id: str) -> str:
    """Absolute local (POSIX) Nextflow workDir for `run_id`.

    The bundled demo always runs the LOCAL executor (see module docstring), so
    the workDir must be a real local path, not `s3://`. Nextflow creates this
    directory itself on launch, so callers don't need to pre-create it.
    """
    return str(_scratch_root(run_id) / "work")


def build_config(run_id: str) -> str:
    """Generate the `nextflow.config` that wires Nextflow's AWS client to B2.

    Region + endpoint come from `B2_REGION` (single source of truth); credentials
    are supplied via the subprocess env, so nothing secret is written to disk.
    """
    return "\n".join(
        [
            "// Generated by Nextflow Genomics Object Storage — do not edit by hand.",
            f"// Run {run_id}. B2 is the S3 backend for reading inputs and",
            "// publishing results (the workDir is local — see service/nextflow.py).",
            "aws {",
            f"    region = '{settings.b2_region}'",
            "    client {",
            f"        endpoint = '{settings.endpoint_url}'",
            "        s3PathStyleAccess = true",
            "    }",
            "}",
            "",
        ]
    )


def build_command(manifest: dict) -> list[str]:
    """Assemble the `nextflow run …` command line.

    `-work-dir` is a LOCAL path (required by the LOCAL executor the bundled demo
    uses); `--outdir` stays on B2 (`s3://…`) so results are still published to
    the data lake — see the module docstring for why these differ.
    """
    run_id = manifest["run_id"]
    bucket = settings.b2_bucket_name
    cmd = [
        settings.nextflow_bin,
        "-log",
        "nextflow.log",
        "run",
        pipeline_source(manifest["pipeline"]),
        "-profile",
        manifest["profile"],
        "-work-dir",
        local_work_dir(run_id),
        "--outdir",
        f"s3://{bucket}/results/{run_id}",
    ]
    if manifest.get("samplesheet"):
        cmd += ["--input", f"s3://{bucket}/{manifest['samplesheet']}"]
    cmd += ["--run_id", run_id]
    return cmd


def _subprocess_env() -> dict:
    env = os.environ.copy()
    env["AWS_ACCESS_KEY_ID"] = settings.b2_application_key_id
    env["AWS_SECRET_ACCESS_KEY"] = settings.b2_application_key
    env["AWS_DEFAULT_REGION"] = settings.b2_region
    env["NXF_ANSI_LOG"] = "false"
    return env


def run_subprocess(cmd: list[str], cwd: str) -> tuple[int, str]:
    """Run Nextflow to completion, returning (exit_code, combined stdout+stderr).

    A test seam: mocked in the suite so verification never shells out to a real
    Nextflow/Java install.
    """
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        env=_subprocess_env(),
        capture_output=True,
        text=True,
        timeout=_RUN_TIMEOUT_SECONDS,
    )
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def _now() -> datetime:
    return datetime.now(UTC)


def execute_run(run_id: str) -> None:
    """Run the pipeline synchronously and persist log + terminal status to B2.

    Called on a background thread by `start_execution`. Never raises: any failure
    is captured into the run's `failed` status and log so the UI can surface it.
    """
    manifest = runs_repo.read_manifest(run_id)
    if manifest is None:
        logger.warning("execute_run: manifest missing for %s", run_id)
        return
    try:
        scratch = _scratch_dir(run_id)
        (scratch / "nextflow.config").write_text(build_config(run_id))
        cmd = build_command(manifest)
        manifest["command"] = " ".join(cmd)
        runs_repo.write_manifest(manifest)
        runs_repo.write_log(run_id, f"$ {' '.join(cmd)}\n\nLaunching Nextflow…\n")
        exit_code, log_text = run_subprocess(cmd, str(scratch))
        runs_repo.write_log(run_id, f"$ {' '.join(cmd)}\n\n{log_text}")
        manifest["exit_code"] = exit_code
        manifest["status"] = "succeeded" if exit_code == 0 else "failed"
        if exit_code != 0:
            manifest["message"] = "Nextflow exited non-zero — see the run log."
    except Exception as exc:
        logger.exception("execute_run failed for %s", run_id)
        manifest["status"] = "failed"
        manifest["message"] = f"Run execution error: {exc}"
        with contextlib.suppress(Exception):
            runs_repo.write_log(run_id, f"Run execution error: {exc}\n")
    finally:
        manifest["finished_at"] = _now()
        manifest["updated_at"] = _now()
        runs_repo.write_manifest(manifest)


def start_execution(run_id: str) -> None:
    """Spawn `execute_run` on a daemon thread so the launch request returns at
    once. A test seam: patched to a no-op when asserting the `running` handoff."""
    import threading

    threading.Thread(
        target=execute_run, args=(run_id,), name=f"nf-run-{run_id}", daemon=True
    ).start()
